# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: drltt_proto/environment/environment.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from drltt_proto.environment import trajectory_tracking_pb2 as drltt__proto_dot_environment_dot_trajectory__tracking__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)drltt_proto/environment/environment.proto\x12\x0b\x64rltt_proto\x1a\x31\x64rltt_proto/environment/trajectory_tracking.proto\"s\n\x0b\x45nvironment\x12L\n\x13trajectory_tracking\x18\x01 \x01(\x0b\x32*.drltt_proto.TrajectoryTrackingEnvironmentH\x00\x88\x01\x01\x42\x16\n\x14_trajectory_trackingb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'drltt_proto.environment.environment_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ENVIRONMENT._serialized_start=109
  _ENVIRONMENT._serialized_end=224
# @@protoc_insertion_point(module_scope)
