# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: drltt_proto/sdk/exported_policy_test_case.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/drltt_proto/sdk/exported_policy_test_case.proto\x12\x0b\x64rltt_proto\"\'\n\x08TensorFP\x12\r\n\x05shape\x18\x01 \x03(\x05\x12\x0c\n\x04\x64\x61ta\x18\x02 \x03(\x02\"\x95\x01\n\x17\x45xportedPolicyTestCases\x12\x30\n\x0cobservations\x18\x01 \x01(\x0b\x32\x15.drltt_proto.TensorFPH\x00\x88\x01\x01\x12+\n\x07\x61\x63tions\x18\x02 \x01(\x0b\x32\x15.drltt_proto.TensorFPH\x01\x88\x01\x01\x42\x0f\n\r_observationsB\n\n\x08_actionsb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'drltt_proto.sdk.exported_policy_test_case_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TENSORFP._serialized_start=64
  _TENSORFP._serialized_end=103
  _EXPORTEDPOLICYTESTCASES._serialized_start=106
  _EXPORTEDPOLICYTESTCASES._serialized_end=255
# @@protoc_insertion_point(module_scope)
