# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: drltt_proto/dynamics_model/action.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'drltt_proto/dynamics_model/action.proto\x12\x0b\x64rltt_proto\"W\n\x06\x41\x63tion\x12;\n\rbicycle_model\x18\x01 \x01(\x0b\x32\x1f.drltt_proto.BicycleModelActionH\x00\x88\x01\x01\x42\x10\n\x0e_bicycle_model\"@\n\x12\x42icycleModelAction\x12\x0e\n\x01\x61\x18\x01 \x01(\x02H\x00\x88\x01\x01\x12\x0e\n\x01s\x18\x02 \x01(\x02H\x01\x88\x01\x01\x42\x04\n\x02_aB\x04\n\x02_sb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'drltt_proto.dynamics_model.action_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ACTION._serialized_start=56
  _ACTION._serialized_end=143
  _BICYCLEMODELACTION._serialized_start=145
  _BICYCLEMODELACTION._serialized_end=209
# @@protoc_insertion_point(module_scope)
