# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: drltt_proto/dynamics_model/hyper_parameter.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0drltt_proto/dynamics_model/hyper_parameter.proto\x12\x0b\x64rltt_proto\"\x9f\x01\n\x0eHyperParameter\x12\x11\n\x04type\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x11\n\x04name\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x43\n\rbicycle_model\x18\x03 \x01(\x0b\x32\'.drltt_proto.BicycleModelHyperParameterH\x02\x88\x01\x01\x42\x07\n\x05_typeB\x07\n\x05_nameB\x10\n\x0e_bicycle_model\"\xa4\x03\n\x1a\x42icycleModelHyperParameter\x12\x13\n\x06length\x18\x01 \x01(\x02H\x00\x88\x01\x01\x12\x1b\n\x0e\x66ront_overhang\x18\x02 \x01(\x02H\x01\x88\x01\x01\x12\x1a\n\rrear_overhang\x18\x03 \x01(\x02H\x02\x88\x01\x01\x12\x16\n\twheelbase\x18\x04 \x01(\x02H\x03\x88\x01\x01\x12\x12\n\x05width\x18\x05 \x01(\x02H\x04\x88\x01\x01\x12\x1e\n\x11\x66rontwheel_to_cog\x18\x06 \x01(\x02H\x05\x88\x01\x01\x12\x1d\n\x10rearwheel_to_cog\x18\x07 \x01(\x02H\x06\x88\x01\x01\x12\x17\n\x0f\x61\x63tion_space_lb\x18\x08 \x03(\x02\x12\x17\n\x0f\x61\x63tion_space_ub\x18\t \x03(\x02\x12\x18\n\x0bmax_lat_acc\x18\n \x01(\x02H\x07\x88\x01\x01\x42\t\n\x07_lengthB\x11\n\x0f_front_overhangB\x10\n\x0e_rear_overhangB\x0c\n\n_wheelbaseB\x08\n\x06_widthB\x14\n\x12_frontwheel_to_cogB\x13\n\x11_rearwheel_to_cogB\x0e\n\x0c_max_lat_accb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'drltt_proto.dynamics_model.hyper_parameter_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HYPERPARAMETER._serialized_start=66
  _HYPERPARAMETER._serialized_end=225
  _BICYCLEMODELHYPERPARAMETER._serialized_start=228
  _BICYCLEMODELHYPERPARAMETER._serialized_end=648
# @@protoc_insertion_point(module_scope)
