# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: drltt_proto/dynamics_model/observation.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,drltt_proto/dynamics_model/observation.proto\x12\x0b\x64rltt_proto\"a\n\x0bObservation\x12@\n\rbicycle_model\x18\x01 \x01(\x0b\x32$.drltt_proto.BicycleModelObservationH\x00\x88\x01\x01\x42\x10\n\x0e_bicycle_model\"*\n\x17\x42icycleModelObservation\x12\x0f\n\x07\x66\x65\x61ture\x18\x01 \x03(\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'drltt_proto.dynamics_model.observation_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _OBSERVATION._serialized_start=61
  _OBSERVATION._serialized_end=158
  _BICYCLEMODELOBSERVATION._serialized_start=160
  _BICYCLEMODELOBSERVATION._serialized_end=202
# @@protoc_insertion_point(module_scope)
