# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: drltt_proto/dynamics_model/state.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from drltt_proto.dynamics_model import basics_pb2 as drltt__proto_dot_dynamics__model_dot_basics__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&drltt_proto/dynamics_model/state.proto\x12\x0b\x64rltt_proto\x1a\'drltt_proto/dynamics_model/basics.proto\"U\n\x05State\x12:\n\rbicycle_model\x18\x01 \x01(\x0b\x32\x1e.drltt_proto.BicycleModelStateH\x00\x88\x01\x01\x42\x10\n\x0e_bicycle_model\"U\n\x11\x42icycleModelState\x12*\n\nbody_state\x18\x01 \x01(\x0b\x32\x16.drltt_proto.BodyState\x12\x0e\n\x01v\x18\x02 \x01(\x02H\x00\x88\x01\x01\x42\x04\n\x02_vb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'drltt_proto.dynamics_model.state_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STATE._serialized_start=96
  _STATE._serialized_end=181
  _BICYCLEMODELSTATE._serialized_start=183
  _BICYCLEMODELSTATE._serialized_end=268
# @@protoc_insertion_point(module_scope)
